project:
  type: website
  output-dir: _site

website:
  title: eyayaw beze
  description: "Eyayaw Beze's personal website"
  site-url: https://eyayaw.github.io
  repo-url: https://github.com/eyayaw/eyayaw.github.io
  twitter-card:
    creator: "@eyayaw"
    card-style: summary_large_image
  open-graph: true
  favicon: social-card.jpg

  navbar:
    background: primary
    left:
      - href: index.qmd
        text: home
      - text: research
        href: research.qmd
      # - text: bio
      #   href: bio.qmd
      - text: cv
        href: cv.qmd
      - text: blog
        href: blog.qmd

    right:
      - icon: envelope
        href: mailto:eyayaw.beze@uni-due.de
      - icon: twitter
        href: https://twitter.com/eyayaw
      - icon: github
        href: https://github.com/eyayaw

  page-footer:
    left: |
      This website is built with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/).

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-title: Contents
    code-copy: true
    code-overflow: wrap
    highlight-style: a11y-dark

execute:
  freeze: auto
editor: source
